// <auto-generated />
using System;
using Despesas.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Despesas.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200907145233_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Despesas.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid?>("MembroFamiliarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid?>("PagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDepesa")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MembroFamiliarId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("Despesa");
                });

            modelBuilder.Entity("Despesas.Domain.Entities.MembroFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveDeAcesso")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChaveDeAcesso");

                    b.ToTable("MembroFamiliar");
                });

            modelBuilder.Entity("Despesas.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("Despesas.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("Despesas.Domain.Entities.MembroFamiliar", "MembroFamiliar")
                        .WithMany()
                        .HasForeignKey("MembroFamiliarId");

                    b.HasOne("Despesas.Domain.Entities.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");
                });

            modelBuilder.Entity("Despesas.Domain.Entities.MembroFamiliar", b =>
                {
                    b.OwnsOne("Despesas.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("MembroFamiliarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasMaxLength(50);

                            b1.HasKey("MembroFamiliarId");

                            b1.ToTable("MembroFamiliar");

                            b1.WithOwner()
                                .HasForeignKey("MembroFamiliarId");
                        });

                    b.OwnsOne("Despesas.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("MembroFamiliarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NomeSocial")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasMaxLength(50);

                            b1.Property<string>("Sobrenome")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasMaxLength(50);

                            b1.HasKey("MembroFamiliarId");

                            b1.ToTable("MembroFamiliar");

                            b1.WithOwner()
                                .HasForeignKey("MembroFamiliarId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
